apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-example-deployment
  labels:
    app: hello-spring-boot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-spring-boot
  template:
    metadata:
      labels:
        app: hello-spring-boot
    spec:
      containers:
      - name: hello-spring-boot
        image: edmundsteele/spring-boot-example-app-personal:latest
        ports:
        - containerPort: 8080