apiVersion: v1
kind: Service
metadata:
  name: hello-spring-boot
spec:
  type: NodePort
  selector:
    app: hello-spring-boot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31111